version: 2

jobs:
  build_frontend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo build frontend
  build_backend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo build backend
  bundle:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo bundle
  test_master:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo test master
  test_latest:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo test latest
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo deploy

workflows:
  version: 2
  build_bundle_test_deploy:
    jobs:
      - build_frontend
      - build_backend
      - bundle:
          requires:
            - build_frontend
            - build_backend
      - test_master:
          requires:
            - bundle
      - test_latest:
          requires:
            - bundle
      - deploy:
          requires:
            - test_master
            - test_latest
